#!/bin/sh

docker-compose build && \
docker-compose up -d && \
sleep 5 && \
docker-compose exec php composer install && \
docker-compose exec mysql mysql -u root -e "CREATE DATABASE colored_balls" && \
sleep 5 && \
docker-compose exec php php artisan migrate;
